import Head from 'next/head'

import styles from '../styles/Home.module.scss'

import CardsList from '../components/cards/cardsList'
import Form from '../components/form/form'
import SearchHistoryList from '../components/searchHistory/searchHistoryList'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Ingredient Explorer</title>
        <meta name="description" content="Food Ingredient Explorer generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Food Ingredient Explorer!
        </h1>

        <Form />

        <SearchHistoryList />

        <CardsList />
      </main>
    </div>
  )
}
