import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Ingredient Explorer</title>
        <meta name="description" content="Food Ingredient Explorer generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Food Ingredient Explorer!
        </h1>
      </main>

      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}
